import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>👋 Lauti 👋</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
        <a href="https://www.instagram.com/lautarocuesta/">lauti!</a>
        </h1>
        <Image
          src="/img.1.jpg"
          alt="Picture of the author"
          width={500}
          height={500}
        />

        <iframe
          src="https://widget.coinlib.io/widget?type=full_v2&theme=light&cnt=6&pref_coin_id=1505&graph=yes"
          width="100%"
          height="409px"
          scrolling="auto"
          marginWidth="0"
          marginHeight="0"
          frameBorder="0"
          border="0"
        ></iframe>
      </main>

      <footer className={styles.footer}>Hey, I am Lauti</footer>
    </div>
  );
}
